// src/lib/valledupar-data.js

export const COMUNAS = [
  { id: "1", nombre: "Comuna 1" },
  { id: "2", nombre: "Comuna 2" },
  { id: "3", nombre: "Comuna 3" },
  { id: "4", nombre: "Comuna 4" },
  { id: "5", nombre: "Comuna 5" },
  { id: "6", nombre: "Comuna 6" },
];

// Datos extraídos de los archivos oficiales: BARRIOS DE VALLEDUPAR POR COMUNAS.xlsx
export const BARRIOS_POR_COMUNA = {
  "1": [
    "ALFONSO LOPEZ", "ALTA GRACIA", "CEREZO", "EL CARMEN", "EL EDEN", "EL PARAISO",
    "EL PESCAITO", "ESPERANZA ORIENTE", "GAITAN", "GUATAPURI", "KENNEDY", "LA GARITA",
    "LA GRANJA", "LAS DELECIAS", "LAS PALMAS", "LOPERENA", "MIRAFLORES", "NUEVA COLOMBIA",
    "PABLO SEXTO", "SAN ANTONIO", "SAN JORGE", "SAN VICENTE", "SANTA ANA (HERNANDO DE SANTANA)",
    "SANTO DOMINGO", "SICARARE", "SOPERENA", "ZAPATO EN MANO", "9 DE MARZO", "11 DE NOVIEMBRE",
    "CENTRO", "HOSPITAL"
  ],
  "2": [
    "12 DE OCTUBRE", "5 DE NOVIEMBRE", "AMANECERES DEL VALLE", "BERMEJA", "CANDELARIA SUR",
    "CDA. CAÑAGUATE", "CENTAURO", "LOS COCOS", "LOS MAYALES", "LOS MILAGROS", "PANAMA",
    "QUINTERO", "SAN FERNANDO", "SAN JORGE", "SANTA RITA", "SANTA ROSA", "SIMON BOLIVAR",
    "URB. BOSQUES DE RANCHO MIO", "URB. CASA E CAMPO", "URB. LAS AMERICAS", "URB. LUIS CARLOS GALAN",
    "URB. MARIA ELENA", "URB. MAYALES", "VERSALLES", "VILLA CASTRO", "VILLA CLARA", "VILLA DEL ROSARIO"
  ],
  "3": [
    "16 DE JULIO", "25 DE DICIEMBRE", "7 DE AGOSTO", "ALTOS DE ZIRUMA 1", "ALTOS DE ZIRUMA 2",
    "ALTOS DE ZIRUMA 3", "ALTOS DE ZIRUMA 4", "ALTOS DE ZIRUMA 5", "ALTOS DEL VALLE",
    "CHIRIQUI", "DON CARMELO", "EL OASIS", "EL PARAMO", "EL PRADO", "LA FE", "LA FELICIDAD",
    "LAS MANUELITAS", "LOS ALAMOS", "LOS FUNDADORES", "MAREIGUA", "NUEVO MILENIO",
    "PRIMERO DE MAYO", "RINCON DE ZIRUMA", "RUEDA", "SAN FRANCISCO", "SAN MARTIN",
    "URB. OGB", "VALLE MEZA", "VILLA CASTRO", "VILLA FUENTES", "VILLA HAYDI", "VILLA LEONOR",
    "VILLA MILE", "VILLA OLGA", "VILLA URIBE"
  ],
  "4": [
    "8 DE DICIEMBRE", "ALAMOS II", "ALAMOS III", "BUENA VISTA", "CASIMIRO MAESTRE",
    "CICARON", "CICERON MAESTRE", "CIUDADELA 450 AÑOS", "CONJUNTO CERRADO LA FONTANA",
    "EDGARDO PUPO", "EL CERRITO", "EL PROGRESO", "FRANCISCO DE PAULA SANTANDER",
    "JORGE DANGOND", "LA MARIGUITA", "LA VICTORIA", "LIMONAR", "LOS CACIQUES",
    "LOS FUNDADORES", "MANANTIAL", "POPULAR", "SABANAS DEL VALLE", "SAN AMRINO",
    "URB. LA FLORESTA", "URB. LAS ACACIAS", "URB. LINDARAJA", "URB. MARIA CAMILA SUR",
    "URB. VALLE HERMOSO", "VILLA ALGENIA", "VILLA CORELCA", "VILLA LUZ", "VILLA MAGDALA",
    "VILLA MARUAMAKE", "VILLA MIRIAM", "VILLA TAXI"
  ],
  "5": [
    "20 DE JULIO", "5 DE ENERO", "ALTOS DE COMFACESAR", "ALTOS DE GARUPAL", "ALTOS DE VILLALBA",
    "ARIZONA", "AZUCAR BUENA", "BELLO HORIZONTE", "CALLEJAS DEL NORTE", "CAMPO ROMERO",
    "CANDELARIA NORTE", "CONCEPCION PEREZ", "CONJUNTO CERRADO", "DIVINO NIÑO", "EL ENEAL",
    "ENRIQUE PUPO MARTINEZ", "FUTURO DE LOS NIÑOS", "GARUPAL ETAPA 1,2,3 Y 4", "LA ESPERANZA",
    "LA NEVADA", "LA POPA", "LA ROCA", "LAS FLORES", "LOS CORTIJOS", "LOS MUSICOS",
    "SAN ISIDRO", "URB. ALTOS DEL ROSARIO", "URB. BALCONES DE SANTA ELENA", "URB. CALLEJAS",
    "URB. CLUB HOUSE", "URB. DUNDAKARE", "URB. LAS MARIAS", "URB. LAS ORQUIDEAS",
    "URB. LOS CORALES", "URB. MARIA CAMILA NORTE", "URB. NUEVA ESPERANZA",
    "URB. PORTAL DEL ROSARIO", "URB. ROSARIO NORTE", "URB. ROSARIO NORTE I",
    "URB. ROSARIO NORTE II", "URB. SANTA ROSA", "URB. SANTO TOMAS", "VILLA CONCHA",
    "VILLA CONSUELO", "VILLA ELVIA", "VILLA FANNY", "VILLA MONICA", "VILLA YANETH", "VILLALBA",
    "ALTOS DE DON ALBERTO", "DON ALBERTO", "VILLA TAYRONA", "FRANCISCO JAVIER"
  ],
  "6": [
    "ALFONSO LOPEZ", "ARREMASSAIN", "CAÑAHUATE", "CHIMILA", "CIUDAD JARDIN",
    "CONJUNTO RESIDENCIAL DEL NORTE", "EDIFICIO SAN JOSE BLOQUES DEL OBRERO", "EL ROCIO",
    "GUAJIRA", "LOS AGUINALDOS", "LOS ANGELES", "LOS CAMPANOS", "NOVALITO", "NUEVO AMANECER",
    "OBRERO", "PASADENA", "PONTEVEDRA", "ROSANIA", "SAN CARLOS", "SAN JERONIMO",
    "SAN JOAQUIN", "SAN VICENTE", "SERRANILLA", "UNIDOS", "URB. MARIA DANIELA",
    "URB. SANTA ROSALIA", "URB. VILLA CALUDIA", "VILLA DEL ROSARIO DEL NORTE"
  ]
};

export const TIPOS_VIA = [
  "Calle", "Carrera", "Diagonal", "Transversal", "Avenida", "Manzana", "Circular"
];